### ISSUE TITLE
"TypeError: menuFlags.includes is not a function" after running git pull and npm install

### ISSUE THREAD

**Issue by XBessa** [NuSkooler/enigma-bbs#109]
For :bug: bug reports, please fill out the information below plus any additional relevant information. If this is a feature request, feel free to clear the form.

Hello, 

After running a "git pull" and "npm install" to upgrade my system, I get the following error message when trying to run main.js: 
System started!
/home/ubuntu/enigma-bbs/core/menu_stack.js:140
                                        if(menuFlags.includes('noHistory')) {
                                                     ^

TypeError: menuFlags.includes is not a function
    at /home/ubuntu/enigma-bbs/core/menu_stack.js:140:19
    at /home/ubuntu/enigma-bbs/core/menu_util.js:114:11
    at /home/ubuntu/enigma-bbs/node_modules/async/dist/async.js:359:16
    at nextTask (/home/ubuntu/enigma-bbs/node_modules/async/dist/async.js:5057:29)
    at /home/ubuntu/enigma-bbs/node_modules/async/dist/async.js:5064:13
    at apply (/home/ubuntu/enigma-bbs/node_modules/async/dist/async.js:21:25)
    at /home/ubuntu/enigma-bbs/node_modules/async/dist/async.js:56:12
    at /home/ubuntu/enigma-bbs/node_modules/async/dist/async.js:843:16
    at createModuleInstance (/home/ubuntu/enigma-bbs/core/menu_util.js:110:12)
    at nextTask (/home/ubuntu/enigma-bbs/node_modules/async/dist/async.js:5070:14)

When I log in, I can see the "ENiGMA 1/2" ANSI page, then the session is disconnected and the above error can be seen. 

**Environment**
- [ ] I am using Node.js v6.x or higher
- [ ] `npm install` reports success
- Actual Node.js version (`node --version`): 4.4.0
- Operating system (`uname -a` on *nix systems): Linux ip-172-31-26-239 3.13.0-92-generic #139-Ubuntu SMP Tue Jun 28 20:42:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Revision (`git rev-parse --short HEAD`): be38bbf

**Expected behavior**

**Actual behavior**

**Steps to reproduce**

**Comment by NuSkooler** [comment]
@XBessa Please see [UPGRADE.md](https://github.com/NuSkooler/enigma-bbs/blob/master/UPGRADE.md) & related release announcements/etc.

As of 0.0.4-alpha+, Node 6.x LTS is required.

**Comment by XBessa** [comment]
Hello, 

I ran the procedures located at UPGRADE.md file but when using sqlite3 I got the following error message: 

sqlite> INSERT INTO message_fts(message_fts) VALUES('rebuild');
Error: no such table: message_fts

Then upon executing main.js: 

ubuntu@ip-172-31-26-239:~/enigma-bbs$ ./main.js
module.js:471
    throw err;
    ^

Error: Cannot find module '/home/ubuntu/enigma-bbs/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/enigma-bbs/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
ubuntu@ip-172-31-26-239:~/enigma-bbs$

**Comment by NuSkooler** [comment]
> I ran the procedures located at UPGRADE.md file but when using sqlite3 I got the following error message:

I think the upgrade instructions need to instruct to run `main.js` (e.g. launch the BBS) once before running the `sqlite3` command such that the table is properly created.

```
Error: Cannot find module '/home/ubuntu/enigma-bbs/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object. (/home/ubuntu/enigma-bbs/node_modules/sqlite3/lib/sqlite3.js:4:15)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
ubuntu@ip-172-31-26-239:~/enigma-bbs$
```

Did you remove `npm_modules` and run `npm install` again after pulling down the latest source (and after upgrading Node.js)?

**Comment by XBessa** [comment]
I did, and the error message remains.

2017-03-02 20:00 GMT-03:00 Bryan Ashby <notifications@github.com>:

**Comment by NuSkooler** [comment]
@XBessa Please try to provide more information. Which error remains? You've shown more than one in this report.

Both errors indicate that you're not running Node.js 6.x+ when launching `main.js`. When launching directly via `./main.js` the *default* Node on your system will be used. I suspect you've installed Node via a package manager or similar in the past. I'd recommend you remove any of them completely and *only* utilize `nvm` for installing Node (`nvm install 6`, `nvm alias default 6`, ...)

If you open up a new shell and type `node --version` what do you get? What happens if you run `node main.js`?

**Comment by XBessa** [comment]
Hello Bryan,

That's weird, because I have followed all the procedures you have
described.

I have Node.js version 6, as you can see as per the outputs below:

ubuntu@ip-172-31-26-239:~/enigma-bbs$ node --version
v6.10.0
ubuntu@ip-172-31-26-239:~/enigma-bbs$ node main.js
module.js:471
    throw err;
    ^

Error: Cannot find module
'/home/ubuntu/enigma-bbs/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous>
(/home/ubuntu/enigma-bbs/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
ubuntu@ip-172-31-26-239:~/enigma-bbs$

2017-03-03 14:45 GMT-03:00 Bryan Ashby <notifications@github.com>:

**Comment by NuSkooler** [comment]
@XBessa Please provide a log of the following:
```
rm -rf node_modules
npm install
```

Also take note if you see errors about building SQLite.

**Comment by NuSkooler** [comment]
@XBessa Any update on this?

**Comment by XBessa** [comment]
You can close the ticket. When I re-did the rm-rf node_modules and the npm
install the system went back online. :)

2017-03-13 23:12 GMT-03:00 Bryan Ashby <notifications@github.com>:

**Comment by NuSkooler** [comment]
@XBessa Beautiful, thanks for updating!
