### ISSUE TITLE
Optutil not working

### ISSUE THREAD

**Issue by apamment** [NuSkooler/enigma-bbs#110]
For :bug: bug reports, please fill out the information below plus any additional relevant information. If this is a feature request, feel free to clear the form.

**Short problem description**
optutil crashes when trying to do anything with the file base

**Environment**
- [X] I am using Node.js v6.x or higher
- [X] `npm install` reports success
- Actual Node.js version (`node --version`): v6.10.0
- Operating system (`uname -a` on *nix systems): Linux zatanna.andrew.homeunix.org 3.10.0-514.10.2.el7.x86_64 #1 SMP Thu Mar 2 11:21:24 CST 2017 x86_64 x86_64 x86_64 GNU/Linux
- Revision (`git rev-parse --short HEAD`):732e2ee

**Expected behavior**
./optutil.js fb scan pc_bbs
Should scan file areas for files
**Actual behavior**
```
/home/andrew/enigma-bbs/core/file_base_area.js:90
	const areaInfo = Config.fileBase.areas[areaTag];
	                       ^

TypeError: Cannot read property 'fileBase' of undefined
    at Object.getFileAreaByTag (/home/andrew/enigma-bbs/core/file_base_area.js:90:25)
    at async.eachSeries (/home/andrew/enigma-bbs/core/oputil/oputil_file_base.js:306:32)
    at /home/andrew/enigma-bbs/node_modules/async/dist/async.js:3025:16
    at replenish (/home/andrew/enigma-bbs/node_modules/async/dist/async.js:881:17)
    at /home/andrew/enigma-bbs/node_modules/async/dist/async.js:885:9
    at eachLimit$1 (/home/andrew/enigma-bbs/node_modules/async/dist/async.js:3114:22)
    at Object.<anonymous> (/home/andrew/enigma-bbs/node_modules/async/dist/async.js:917:16)
    at scanAreas (/home/andrew/enigma-bbs/core/oputil/oputil_file_base.js:305:11)
    at /home/andrew/enigma-bbs/node_modules/async/dist/async.js:3686:9
    at replenish (/home/andrew/enigma-bbs/node_modules/async/dist/async.js:881:17)
```
**Steps to reproduce**

**Comment by NuSkooler** [comment]
Fixed @ d6e5dcbdf13cd88b90c7ac518fb110a191630878
