### ISSUE TITLE
Crash in MultiLineTextEditView when using pipe codes

### ISSUE THREAD

**Issue by NuSkooler** [NuSkooler/enigma-bbs#147]
Reported by a user:
```
I went to type out a test message and on the first line once it reached the  
end, Enigma crashed and gave this error:                                     
                                                                             
home/pi/enigma-bbs/core/multi_line_edit_text_view.js:437                     
    if(lastCol >= firstWrapRange.start && lastCol <=firstWrapRange.end) {    
                                ^                                            
                                                                             
TypeError: Cannot read property 'start' of undefined                         
    at MultiLineEditTextView.insertCharactersInText                          
(/home/pi/enigma-bbs/core/multi_line_edit_text_view.js:437:32)               
    at MultiLineEditTextView.keyPressCharacter                               
(/home/pi/enigma-bbs/core/multi_line_edit_text_view.js:661:9)                
    at MultiLineEditTextView.onKeyPress                                      
(/home/pi/enigma-bbs/core/multi_line_edit_text_view.js:1182:8)               
    at TelnetClient.ViewController.clientKeyPressHandler                      
(/home/pi/enigma-bbs/core/view_controller.js:83:22)                           
    at emitTwo (events.js:111:20)                                             
    at TelnetClient.emit (events.js:191:7)                                    
    at bufPart (/home/pi/enigma-bbs/core/client.js:393:11)                    
    at Array.forEach (native)                                                 
    at TelnetClient.clientData (/home/pi/enigma-bbs/core/client.js:275:7)     
    at emitOne (events.js:96:13)                                              
    at TelnetClient.emit (events.js:188:7)                                    
                                                                              
Is this something not setup on my system?                                     

Okay so I figured out how to cause it to do this crash. I tested writing a      
message today no problems at all. However, last night in my initial test        
message I entered a pipe color code just to see if it would work and by the     
time I got to the end of the line, it spit out that error and crashed. Again,   
today I tested entering a |08and |07carried on with the message to the end of   
the line and it crashed again...
```

Actual problem is half baked handling of pipe color codes in some areas of the code base, but not the others. E.g. MLTEV (or FSE using it) wants to wrap, but wrap code takes into account pipe and ANSI escape sequences. Things go bad. Kaboom.

**Comment by NuSkooler** [comment]
Another stack
```
0|xibalba  | TypeError: Cannot read property 'start' of undefined
0|xibalba  |     at MultiLineEditTextView.insertCharactersInText (/home/enigma/xibalba/core/multi_line_edit_text_view.js:434:42)
0|xibalba  |     at MultiLineEditTextView.keyPressCharacter (/home/enigma/xibalba/core/multi_line_edit_text_view.js:656:18)
0|xibalba  |     at MultiLineEditTextView.onKeyPress (/home/enigma/xibalba/core/multi_line_edit_text_view.js:1177:14)
0|xibalba  |     at SSHClient.ViewController.clientKeyPressHandler (/home/enigma/xibalba/core/view_controller.js:90:34)
0|xibalba  |     at SSHClient.emit (events.js:210:5)
0|xibalba  |     at bufPart (/home/enigma/xibalba/core/client.js:434:26)
0|xibalba  |     at Array.forEach (<anonymous>)
0|xibalba  |     at SSHClient.clientData (/home/enigma/xibalba/core/client.js:316:13)
0|xibalba  |     at SSHClient.emit (events.js:210:5)
0|xibalba  |     at Channel.SSHClient.dataHandler (/home/enigma/xibalba/core/servers/login/ssh.js:206:14)
```

**Comment by NuSkooler** [comment]
https://github.com/NuSkooler/enigma-bbs/issues/148
