### ISSUE TITLE
Crash on delete in BBS List with zero entries

### ISSUE THREAD

**Issue by Jasin2069** [NuSkooler/enigma-bbs#156]
If there are zero entries and you hit D engima crashes
**Short problem description**
enigma\core\bbs_list.js:104
                                if(self.entries[self.selectedBBS].submitterUserId !== self.client.user.userId && !self.client.user.isSysOp()) {
                                                                  ^

TypeError: Cannot read property 'submitterUserId' of undefined
    at Object.deleteBBS (D:\enigma\core\bbs_list.js:104:39)
    at Object.handleAction (D:\enigma\core\menu_util.js:210:57)
    at ViewController.handleActionWrapper (D:\enigma\core\view_controller.js:48:12)
    at TelnetClient.ViewController.clientKeyPressHandler (D:\enigma\core\view_controller.js:77:10)
    at emitTwo (events.js:126:13)
    at TelnetClient.emit (events.js:214:7)
    at bufPart (D:\enigma\core\client.js:393:11)
    at Array.forEach (<anonymous>)
    at TelnetClient.clientData (D:\enigma\core\client.js:275:7)
    at emitOne (events.js:116:13)

**Expected behavior**
should do nothing or state there is nothing to delete
**Actual behavior**
tries to delete a null entry
**Steps to reproduce**
press D in bbslist with no entries

**Comment by Jasin2069** [comment]
This crash also seems to happen when pressing d without changing. I added a bunch of fake bbs's then when first going to the bbs menu and hitting d. The info to the right shows the selected bbs.

**Comment by NuSkooler** [comment]
@Jasin2069 which branch are you using? I've pushed a fix to `0.0.9-alpha` but can some some cherry picking into `0.0.8-alpha` (master) if that's what you're using.
