### ISSUE TITLE
Crash on assert(this.patternArrayPos >= 0) in nua.js

### ISSUE THREAD

**Issue by richinseattle** [NuSkooler/enigma-bbs#202]
Enigma 0.0.9-alpha 
Node v10.6.0

**Short problem description**
Failed assert in NUA, no repro. node --debug apparently detached on its own due to assert? so I couldn't inspect variables 
  
```
[2018-07-18T04:08:08.182Z] DEBUG: ENiGMA½ BBS/9570 on undercurrents-bbs: Ignoring command (clientId=0, sessionId=b1fzwzBMA7a)
    evt: {
      "commandCode": 240,
      "command": "se",
      "buf": {
        "type": "Buffer",
        "data": [
          255,
          240
        ]
      }
    }
[2018-07-18T04:08:08.250Z] DEBUG: ENiGMA½ BBS/9570 on undercurrents-bbs: Set known terminal client (termClient=vtx)
[2018-07-18T04:08:08.754Z] DEBUG: ENiGMA½ BBS/9570 on undercurrents-bbs: Goto menu module (clientId=0, sessionId=b1fzwzBMA7a, menuName=telnetConnected)
[2018-07-18T04:08:11.261Z] DEBUG: ENiGMA½ BBS/9570 on undercurrents-bbs: Goto menu module (clientId=0, sessionId=b1fzwzBMA7a, menuName=loginMatrix)
[2018-07-18T04:08:16.969Z] DEBUG: ENiGMA½ BBS/9570 on undercurrents-bbs: Goto menu module (clientId=0, sessionId=b1fzwzBMA7a, menuName=newUserApplicationPre)
[2018-07-18T04:08:48.546Z] DEBUG: ENiGMA½ BBS/9570 on undercurrents-bbs: Goto menu module (clientId=0, sessionId=b1fzwzBMA7a, menuName=newUserApplication)

--

< assert.js:269
<     throw err;
<     ^
< AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
<   assert(this.patternArrayPos >= 0)
<     at MaskEditTextView.onKeyPress (/undercurrents-bbs/core/mask_edit_text_view.js:128:17)
<     at WebSocketClient.ViewController.clientKeyPressHandler (/undercurrents-bbs/core/view_controller.js:88:34)
<     at WebSocketClient.emit (events.js:182:13)
<     at bufPart (/undercurrents-bbs/core/client.js:411:26)
<     at Array.forEach (<anonymous>)
<     at WebSocketClient.clientData (/undercurrents-bbs/core/client.js:293:13)
<     at WebSocketClient.emit (events.js:182:13)
<     at SocketBridge.TelnetClient.dataHandler (/undercurrents-bbs/core/servers/login/telnet.js:536:18)
<     at SocketBridge.emit (events.js:182:13)
<     at WebSocketClient.dataHandler (/undercurrents-bbs/core/servers/login/websocket.js:37:31)
< Waiting for the debugger to disconnect...
debug>
```

**Comment by richinseattle** [comment]
Looking further back in the logs, it looks like this connection was made through VTX.. it looks like the log entry about Buffer is not that uncommon from grepping my logs, this is the first crash caused by it that I'm aware of, but have only recently been running under a debugger

```
[2018-07-18T04:08:08.051Z]  INFO: ENiGMA½ BBS/9570 on undercurrents-bbs: Client connected (clientId=0, sessionId=b1fzwzBMA7a, remoteAddress=::[redacted], serverName=WebSocket, isSecure=true)
[2018-07-18T04:08:08.118Z] DEBUG: ENiGMA½ BBS/9570 on undercurrents-bbs: Telnet: Window size updated (clientId=0, sessionId=b1fzwzBMA7a, termWidth=80, termHeight=25, source=NAWS)
[2018-07-18T04:08:08.181Z] DEBUG: ENiGMA½ BBS/9570 on undercurrents-bbs: Set output encoding due to terminal type change (encoding=cp437)
[2018-07-18T04:08:08.181Z] DEBUG: ENiGMA½ BBS/9570 on undercurrents-bbs: Set terminal type (clientId=0, sessionId=b1fzwzBMA7a, termType=ansi-bbs)
[2018-07-18T04:08:08.181Z] DEBUG: ENiGMA½ BBS/9570 on undercurrents-bbs: Set client theme (clientId=0, sessionId=b1fzwzBMA7a, setThemeId=undercurrents-toorcamp, requestedThemeId=undercurrents-toorcamp)
    info: {
      "name": "uc",
      "author": "various",
      "group": "fuel",
      "enabled": true,
      "themeId": "undercurrents-toorcamp"
    }
```

**Comment by NuSkooler** [comment]
`SE` is "End of sub-negotiation". I'm *guessing* that something is being broken up across buffers and there is a slight miss-handling, but it shouldn't really cause the issue you're seeing.

Assert in question checks that the potion in the mask array (of MaskEdit) is valid. I'll see if I can dupe both issues though.

**Comment by NuSkooler** [comment]
@richinseattle Were you ever able to get more info on this? I've yet to see it / reproduce it.

**Comment by NuSkooler** [comment]
Closing due to inactivity. Can be re-opened if it's seen again.
