### ISSUE TITLE
Crash using VTX Client

### ISSUE THREAD

**Issue by flewid** [NuSkooler/enigma-bbs#284]
Had a buddy try to connect via VTX today and i received a crash. 

:30,"remoteAddress":"::ffff:IP_ADD_RESS_HERE","serverName":"WebSocket","isSecure":true,"msg":"Client connected","time":"2020-06-01T19:11:31.803Z","v":0}
{"name":"ENiGMA½ BBS","hostname":"lofi.ooo","pid":20783,"level":30,"connectionCount":0,"nodeId":1,"msg":"Client disconnected","time":"2020-06-01T19:11:37.329Z","v":0}
/home/enigma/enigma-bbs-beta/core/servers/chat/mrc_multiplexer.js:298
    return message.replace(/[^\x21-\x7D]|(\|\w\w)/g, '').substr(0, 30);
                   ^

TypeError: Cannot read property 'replace' of undefined
    at sanitiseRoomName (/home/enigma/enigma-bbs-beta/core/servers/chat/mrc_multiplexer.js:298:20)
    at MrcModule.sendToMrcServer (/home/enigma/enigma-bbs-beta/core/servers/chat/mrc_multiplexer.js:267:13)
    at MrcModule.receiveFromClient (/home/enigma/enigma-bbs-beta/core/servers/chat/mrc_multiplexer.js:256:14)
    at data.toString.split.forEach.item (/home/enigma/enigma-bbs-beta/core/servers/chat/mrc_multiplexer.js:169:30)
    at Array.forEach (<anonymous>)
    at Socket.socket.on.data (/home/enigma/enigma-bbs-beta/core/servers/chat/mrc_multiplexer.js:160:54)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:265:13)
    at Socket.Readable.push (_stream_readable.js:224:10)

**Comment by NuSkooler** [comment]
Looks like a chunk could come in, fail to parse, but still be sent along. Hopefully good now.
