### ISSUE TITLE
Fresh install failing 

### ISSUE THREAD

**Issue by xianoth** [NuSkooler/enigma-bbs#298]
For :bug: bug reports, please fill out the information below plus any additional relevant information. If this is a feature request, feel free to clear the form.

When installing the BBS via the *nix install script, the installation failed.

**Environment**
- [ ] I am using Node.js v12.x LTS or higher
- [ ] `npm install` or `yarn` reports success
- Actual Node.js version (`node --version`): v12.18.3
- Operating system (`uname -a` on *nix systems): 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Revision (`git rev-parse --short HEAD`): 

**Expected behavior**
Successful installation

**Actual behavior**
Failed due to build error

**Steps to reproduce**
Ran install script

Notes:
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/obie/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-42-generic
gyp ERR! command "/home/obie/.nvm/versions/node/v12.18.3/bin/node" "/home/obie/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/obie/enigma-bbs/node_modules/node-pty
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty@0.9.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by NuSkooler** [comment]
@xianoth is this still happening?

What happens if you just type `npm install` (or `yarn` if using that) from the enigma-bbs dir?
