### ISSUE TITLE
Unable to create config file.

### ISSUE THREAD

**Issue by mrhatestheworld** [NuSkooler/enigma-bbs#303]
For :bug: bug reports, please fill out the information below plus any additional relevant information. If this is a feature request, feel free to clear the form.

**Short problem description**
Unable to create initial configuration file.
**Environment**
- [ x] I am using Node.js v12.x LTS or higher
- [ ] `npm install` or `yarn` reports success
- Actual Node.js version (`node --version`):
- Operating system (`uname -a` on *nix systems): Ubuntu
- Revision (`git rev-parse --short HEAD`): f558a61

**Expected behavior**
Config file is created
**Actual behavior**
internal/modules/cjs/loader.js:1083
  throw err;
  ^

Error: Cannot find module '/root/enigma-bbs/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node'
Require stack:
- /root/enigma-bbs/node_modules/sqlite3/lib/sqlite3-binding.js
- /root/enigma-bbs/node_modules/sqlite3/lib/sqlite3.js
- /root/enigma-bbs/core/database.js
- /root/enigma-bbs/core/oputil/oputil_common.js
- /root/enigma-bbs/core/oputil/oputil_main.js
- /root/enigma-bbs/oputil.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)
    at Function.Module._load (internal/modules/cjs/loader.js:923:27)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/root/enigma-bbs/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/enigma-bbs/node_modules/sqlite3/lib/sqlite3-binding.js',
    '/root/enigma-bbs/node_modules/sqlite3/lib/sqlite3.js',
    '/root/enigma-bbs/core/database.js',
    '/root/enigma-bbs/core/oputil/oputil_common.js',
    '/root/enigma-bbs/core/oputil/oputil_main.js',
    '/root/enigma-bbs/oputil.js'
  ]
}
**Steps to reproduce**
./oputil.js config new

**Comment by robbiew** [comment]
Pretty sure this happened to me... I think `apt-get install sqlite3 libsqlite3-dev` and then `npm install` solved it?

**Comment by mrhatestheworld** [comment]
That worked perfectly. Thank you!

**Comment by NuSkooler** [comment]
You really shouldn't run into something like this if you close / re-open your shell after the `install.sh` (assuming it completed without error). Part of the install installs modules. The node version that the install used is from NVM and needs to be the same Node version that `oputil.js` ends up using. 

Make sure you don't have an alternative (e.g. apt installed) Node.js. Ensure the Node.js version you're getting when you `which node` is from NVM. If those are right and you have issues, cd to the enigma-bbs dir and type `npm install` then try again (or report any error kicked out there)

**Comment by NuSkooler** [comment]
Closing due to inactivity. A install.sh update was pushed recently + this sounds like the terminal was not reopened (which is not better brought to the users attention)
