### ISSUE TITLE
Private Messages cannot be deleted

### ISSUE THREAD

**Issue by blackmagic-consult** [NuSkooler/enigma-bbs#309]
Hi NuSkooler,

I'm having a glitch on the Private Messages pages. When the delete keys are pressed, and @method:deleteSelected is called, this error occurs:

[2020-08-26T21:35:53.127Z] TRACE: ENiGMA½ BBS/469183 on panoptic.onl: Action match (nodeId=1, sessionId=Q1UgY4nb1z0, username=tonic)
    actionBlock: {
      "keys": [
        "delete",
        "d",
        "shift + d"
      ],
      "action": "@method:deleteSelected"
    }
[2020-08-26T21:35:53.133Z]  WARN: ENiGMA½ BBS/469183 on panoptic.onl: Error during handleAction() (nodeId=1, sessionId=Q1UgY4nb1z0, username=tonic, err.code=-32009)
    EnigError: Missing required MCI code(s): Missing prompt XY2 MCI
        at Object.MissingMci (/home/tonic/enigma-bbs/core/enig_error.js:38:52)
        at MessageListModule.promptConfirmDelete (/home/tonic/enigma-bbs/core/msg_list.js:397:30)
        at /home/tonic/enigma-bbs/core/msg_list.js:390:25
        at /home/tonic/enigma-bbs/core/message.js:654:24
        at /home/tonic/enigma-bbs/node_modules/async/dist/async.js:2955:19
        at wrapper (/home/tonic/enigma-bbs/node_modules/async/dist/async.js:268:20)
        at replenish (/home/tonic/enigma-bbs/node_modules/async/dist/async.js:435:29)
        at iterateeCallback (/home/tonic/enigma-bbs/node_modules/async/dist/async.js:424:21)
        at /home/tonic/enigma-bbs/node_modules/async/dist/async.js:321:20
        at /home/tonic/enigma-bbs/node_modules/async/dist/async.js:2953:17

**Environment**
- [x] `npm install` or `yarn` reports success
- [x] I am using Node.js v12.x LTS or higher
- Actual Node.js version (`node --version`): v12.18.3
- Operating system (`uname -a` on *nix systems): Linux panoptic.onl 5.4.0-42-generic #46-Ubuntu SMP x86_64 GNU/Linux
- Revision (`git rev-parse --short HEAD`): 38890b6

**Expected behavior**
The delete message dialog box is called

**Actual behavior**
Nothing happens
**Steps to reproduce**
Receive any message in your Private Inbox and try to delete it.

**Comment by NuSkooler** [comment]
The default art for the message list is `PRVMSGLIST.ANS` and contains `%XY2` for the "Are you sure" prompt placement which is what cannot be found in your log above. Did you create new art for this?

**Comment by blackmagic-consult** [comment]
Somehow I replaced %XY2 with %XYZ

Thanks, not sure how I missed this
