### ISSUE TITLE
Failed writing to socket

### ISSUE THREAD

**Issue by jamespdaily** [NuSkooler/enigma-bbs#356]
Hey guys, getting enigma up and running using a docker-compose and I've gotten the server deployed but I'm having some issues.

Once Engima is up and running I try to telnet to the BBS and it connects, shows the "Connected to enigma" screen for about a half second then immediately disonnects

Checking the logs I see these following errors

`{"name":"ENiGMA½ BBS","hostname":"885874a73efe","pid":18,"nodeId":1,"sessionId":"l9UVvMJyXkr","level":50,"err":{"message":"Object does not exist: No menu entry for \"telnetConnected\"","name":"EnigError","stack":"EnigError: Object does not exist: No menu entry for \"telnetConnected\"\n    at Object.DoesNotExist (/enigma-bbs/core/enig_error.js:31:52)\n    at locateMenuConfig (/enigma-bbs/core/menu_util.js:32:40)\n    at nextTask (/enigma-bbs/node_modules/async/dist/async.js:4576:27)\n    at Object.waterfall (/enigma-bbs/node_modules/async/dist/async.js:4587:9)\n    at Object.awaitable [as waterfall] (/enigma-bbs/node_modules/async/dist/async.js:208:32)\n    at getMenuConfig (/enigma-bbs/core/menu_util.js:24:11)\n    at getMenuConfiguration (/enigma-bbs/core/menu_util.js:60:17)\n    at nextTask (/enigma-bbs/node_modules/async/dist/async.js:4576:27)\n    at Object.waterfall (/enigma-bbs/node_modules/async/dist/async.js:4587:9)\n    at Object.awaitable [as waterfall] (/enigma-bbs/node_modules/async/dist/async.js:208:32)","code":-33002},"msg":"Object does not exist: No menu entry for \"telnetConnected\"","time":"2021-05-18T00:57:41.448Z","v":0}
{"name":"ENiGMA½ BBS","hostname":"885874a73efe","pid":18,"level":40,"error":"write after end","msg":"Failed writing to socket","time":"2021-05-18T00:57:41.449Z","v":0}
{"name":"ENiGMA½ BBS","hostname":"885874a73efe","pid":18,"level":40,"error":"Cannot call write after a stream was destroyed","msg":"Failed writing to socket","time":"2021-05-18T00:57:41.450Z","v":0}
{"name":"ENiGMA½ BBS","hostname":"885874a73efe","pid":18,"level":40,"error":"Cannot call write after a stream was destroyed","msg":"Failed writing to socket","time":"2021-05-18T00:57:41.450Z","v":0}
{"name":"ENiGMA½ BBS","hostname":"885874a73efe","pid":18,"level":40,"modInfo":{"name":"Telnet","desc":"Telnet Server v2","author":"NuSkooler","isSecure":false,"packageName":"codes.l33t.enigma.telnet.server.v2"},"error":"write after end","msg":"Client socket error","time":"2021-05-18T00:57:41.450Z","v":0}
`

I created a pastebin for my docker compose here: https://pastebin.com/Xp8iW90F

Note that PUID 113 is a system user that owns the enigma-bbs folder

not sure how to approach this, any help is appreciated thanks!

**Comment by NuSkooler** [comment]
Is this the same person asking in IRC the other day?

@davestephens Any ideas?

**Comment by NuSkooler** [comment]
@jamespdaily Another user reported something similar with Docker. TBH I haven't used the official container, this is by RiPuk aka @davestephens. I know others are using Docker however. IRC may be a way to get things moving quicker -- also try on fsxNet enigma group as I know some Docker users are there.

I will try to make time to setup a test myself, but my time is extremely limited right now due to brand new job and such.

**Comment by jamespdaily** [comment]
Hey, no problem, I'll look to IRC for help then. Good luck with the new job!

**Comment by matthew-parlette** [comment]
I just got around this today, if you are using the docker container and the instructions to mount the various directories, then you most likely have an empty art directory in your container.

To fix this, I copied all of the art files (keeping the directory structure for the themes) from the repo into my art directory that is mounted in the docker container as `/enigma-bbs/art`.

There are some ways to fix the docker container to work around this, so I'll try to get something in place and add a PR, but this workaround did the trick for me.

Let me know if you need any more details!

**Comment by NuSkooler** [comment]
@matthew-parlette You might want to check out the latest container work that's been pushed.

**Comment by NuSkooler** [comment]
I'll try start looking at this soon, but definitely welcome help!

**Comment by NuSkooler** [comment]
Closing due to inactivity and comments above regarding Docker/mounting.
