### ISSUE TITLE
Bad layout on New User Application crashes BBS

### ISSUE THREAD

**Issue by cognitivegears** [NuSkooler/enigma-bbs#373]
**Describe the Bug**
When designing the New User application screen, it isn't clear from the documentation that need to happen:

* The username must be in view 1
* The password must be in view 9, and the confirmation in view 10
* Nothing can be in view 11, since that is hard coded for error messages

**To Reproduce**
Create a new user application menu with a password that is not in field 9, the confirmation is not in view 10, or has any view definition for view 11.

**Expected Behavior**
Unknown if all of this is possible, but some ideas:

For the passwords, it could look up the fields that have "password: true" in the form to compare instead of hard-coding. For field 11, a MCI type could be used specifically for error message so that it can be found.

Alternatively, if these are not possible, just documenting this in comments in the <boardname>-new_user.hjson and/or in the main documentation would save time having to look into the source code to discover the reason for the error.

**Actual Behavior**
All of these result in the application hard crashing, below are the error messages I captured:

Using a different view id for password:
/home/cognitivegears/enigma-bbs/core/nua.js:44
                return cb(passwordView.getData() === data ? null : new Error('Passwords do not match'));
                                       ^

TypeError: Cannot read property 'getData' of undefined
    at EditTextView.validatePassConfirmMatch [as validate] (/home/cognitivegears/enigma-bbs/core/nua.js:44:40)
    at ViewController.validateView (/home/cognitivegears/enigma-bbs/core/view_controller.js:357:18)
    at ViewController.switchFocus (/home/cognitivegears/enigma-bbs/core/view_controller.js:470:10)
    at ViewController.nextFocus (/home/cognitivegears/enigma-bbs/core/view_controller.js:498:14)
    at EditTextView.ViewController.viewActionListener (/home/cognitivegears/enigma-bbs/core/view_controller.js:99:22)
    at EditTextView.emit (events.js:314:20)
    at EditTextView.View.onKeyPress (/home/cognitivegears/enigma-bbs/core/view.js:276:18)
    at EditTextView.onKeyPress (/home/cognitivegears/enigma-bbs/core/edit_text_view.js:83:46)
    at TelnetClient.ViewController.clientKeyPressHandler (/home/cognitivegears/enigma-bbs/core/view_controller.js:90:34)
    at TelnetClient.emit (events.js:314:20)

Using a field as field 11 in the form:

assert.js:386
    throw err;
    ^

AssertionError [ERR_ASSERTION]: View with ID 11 already exists
    at ViewController.addView (/home/cognitivegears/enigma-bbs/core/view_controller.js:416:5)
    at /home/cognitivegears/enigma-bbs/core/view_controller.js:157:22
    at /home/cognitivegears/enigma-bbs/node_modules/async/dist/async.js:2154:44
    at eachOfArrayLike (/home/cognitivegears/enigma-bbs/node_modules/async/dist/async.js:500:13)
    at eachOf (/home/cognitivegears/enigma-bbs/node_modules/async/dist/async.js:551:16)
    at awaitable (/home/cognitivegears/enigma-bbs/node_modules/async/dist/async.js:208:32)
    at Object.eachLimit (/home/cognitivegears/enigma-bbs/node_modules/async/dist/async.js:2216:16)
    at Object.awaitable (/home/cognitivegears/enigma-bbs/node_modules/async/dist/async.js:208:32)
    at ViewController.createViewsFromMCI (/home/cognitivegears/enigma-bbs/core/view_controller.js:148:15)
    at createViews (/home/cognitivegears/enigma-bbs/core/view_controller.js:701:22) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

**Screenshots**
See above for error messages on the command line.

**Environment**
* [ X ] I am using Node.js v12.x LTS or higher
* [ X ] `npm install` or `yarn` reports success
* Actual Node.js version (`node --version`):
v12.22.7

* Operating system (`uname -a` on *nix systems):
Linux pop-os 5.15.5-76051505-generic #202111250933~1638201579~21.10~09f1aa7 SMP Mon Nov 29 16:23:13 U x86_64 x86_64 x86_64 GNU/Linux

* Revision (`git rev-parse --short HEAD`):
ef65651

* Any additional relevant information about your setup
Nothing

**Comment by cognitivegears** [comment]
Just to add, I have personally worked past these issues by renaming the views on NUA. Creating the issue as it might help others who are starting with Enigma 1/2 to address these.

**Comment by NuSkooler** [comment]
@cognitivegears This is a area that needs a *lot* of additional documentation for sure. Newer versions can also look up fields by name, which would be great for this sort of thing. ie: Your MCI codes can be mapped to a name (in your menu.hjson) so in code you can look them up by that. 

I plan on doing some touch up work soon, and hopefully clean up some pending features. I've been so busy with other stuff I haven't even logged into my board in forever :(

**Comment by cognitivegears** [comment]
Thanks! Selecting these by name would work fantastic. Since I put in this issue, I've been seeing this on a ton of other modules as well. I was able to work around it on NUA, but on the user configuration module for example, all of the IDs are hard-coded because it uses them to populate the current values. Since that is also used for the tab order, it does mean that screens can't have elements reordered (without the cursor jumping around) currently.

And no worries - I know what it's like on time! Once you get to this, if you want to do one of the modules so I know what direction you'd like to take, I'd be happy to help with PRs for others as well if that helps.

**Comment by NuSkooler** [comment]
@cognitivegears I guess I *thought* I had written by-name lookup, but I guess not (why?!). I'll try to take a look at this soon.

**Comment by NuSkooler** [comment]
@cognitivegears Can we close this one? As far as by-name lookup, I think that's something that can be tracked separately. Feel free to create a ticket for it. I don't think the implementation would be too terribly bad.

**Comment by cognitivegears** [comment]
@NuSkooler sounds good to me. By the way, I know I owe you some more code too btw - sorry I got distracted with another project for a bit, but I should be able to pick back up on it soon. All the recent changes are fantastic too, and thanks for the shout-out!
