### ISSUE TITLE
I updated enigma and now ./main.js will not run because of a syntax error

### ISSUE THREAD

**Issue by Urban-Hacker** [NuSkooler/enigma-bbs#416]
**Describe the Bug**
I updated my installation on Enigma and now I have the following error:
/home/ubuntu/enigma-bbs2/core/theme.js:588
                if(_.isNumber(options?.position?.row)) {
                                      ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at initMenusAndThemes (/home/ubuntu/enigma-bbs2/core/bbs.js:226:42)
    at /home/ubuntu/enigma-bbs2/node_modules/async/dist/async.js:3669:28
    at replenish (/home/ubuntu/enigma-bbs2/node_modules/async/dist/async.js:446:21)

**To Reproduce**
I tried to clone into a new folder to end up in the same situation

**Environment**
* [x] I am using Node.js v12.x LTS or higher
* [x] `npm install` or `yarn` reports success
* Actual Node.js version (`node --version`): v12.22.12
* Operating system (`uname -a` on *nix systems): Ubuntu 5.4.0-88-generic 
* Revision (`git rev-parse --short HEAD`): ac010f2c

**Comment by NuSkooler** [comment]
That came out a bit garbled from my phone. Please see the latest `UPDATE.md`. Node.js 14+ is now required.
