### ISSUE TITLE
MODULE_NOT_FOUND sqlite3-binding

### ISSUE THREAD

**Issue by oilcan-productions** [NuSkooler/enigma-bbs#434]
**Describe the Bug**
After a clean new install I am getting an error when running main.js after creating a new config.

```
./main.js 
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/home/pi/enigma-bbs/node_modules/sqlite3/lib/binding/node-v72-linux-arm/node_sqlite3.node'
Require stack:
- /home/pi/enigma-bbs/node_modules/sqlite3/lib/sqlite3-binding.js
- /home/pi/enigma-bbs/node_modules/sqlite3/lib/sqlite3.js
- /home/pi/enigma-bbs/core/database.js
- /home/pi/enigma-bbs/core/bbs.js
- /home/pi/enigma-bbs/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/pi/enigma-bbs/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/enigma-bbs/node_modules/sqlite3/lib/sqlite3-binding.js',
    '/home/pi/enigma-bbs/node_modules/sqlite3/lib/sqlite3.js',
    '/home/pi/enigma-bbs/core/database.js',
    '/home/pi/enigma-bbs/core/bbs.js',
    '/home/pi/enigma-bbs/main.js'
  ]
}

```
I checked and there is only a '/home/pi/enigma-bbs/node_modules/sqlite3/lib/binding/node-v83-linux-arm/node_sqlite3.node'
**To Reproduce**
Any relevant steps to reproduce the behavior:
Install on Rpi 4 using install.sh
create new config
run main.js

**Expected Behavior**
BBS to start
**Actual Behavior**
Error happens

**Screenshots**

**Environment**
* [ X] I am using Node.js v14.x LTS or higher
* [ X] `npm install` or `yarn` reports success (though lots of warning
* Actual Node.js version (`node --version`): v14.19.3
* Operating system (`uname -a` on *nix systems): Linux rpi-400 5.15.32-v7l+ #1538 SMP Thu Mar 31 19:39:41 BST 2022 armv7l GNU/Linux
* Revision (`git rev-parse --short HEAD`): c1311f06
* Any additional relevant information about your setup

**Comment by oilcan-productions** [comment]
I got this fixed, it is due to a version mismatch between the node version installed (even if it is 14+) and the built sqlite modules.
To fix this I had to do the following:
```
cd ~/enigma-bbs (the folder you installed into)
rm -rf node-modules
# get node to v14
sudo apt update
curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
sudo apt install -y nodejs
# grab the latest v14 LTS, get the version number by nvm list-remote
nvm install v14.19.3

# install and re-build the modules
npm install
rpm rebuild
```

now the BBS is launching as expected
