### ISSUE TITLE
install script method fails when trying to run ./main.js Unexpected token '.'  ansi_escape_parser.js:42     this.row = Math.min(options?.startRow ?? 1, this.termHeight);

### ISSUE THREAD

**Issue by rcmart3q** [NuSkooler/enigma-bbs#455]
**Describe the Bug**
after installing on Ubuntu 22.04 via the install script, I try to run main.js and it fails to load with the following error:

```/home/admin/enigma-bbs/core/ansi_escape_parser.js:42
    this.row = Math.min(options?.startRow ?? 1, this.termHeight);
                                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/admin/enigma-bbs/core/ansi_prep.js:5:26)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
admin@seven-bbs:~/enigma-bbs$ 
``

**To Reproduce**
on Ubuntu 22.04 run the install script and try launching main.js

**Expected Behavior**
main.js should launch as indicated in documentation


**Environment**
* Ubuntu 22.04 fresh install on intel Nuc
* node version: v12.22.12
* Operating system: 5.4.0-126-generic #142-Ubuntu SMP

**Comment by rcmart3q** [comment]
So it appears that the documentation is dated, under the Manual install section it directs the admin to run the install script but verify the current version of NVM which at this time is `0.39.1`. 

But then instructs to install node 12 with the below commands:

**Next, install Node.js with NVM:**
```nvm install 12
nvm use 12
nvm alias default 12```

While there is a note at the top of Manual Installation page under prerequisites, stating that any version above 14.x LTS should work, I have verified that main.js fails to load with a different error on node 16.x LTS. 

[Node.js](https://nodejs.org/) version v14.x LTS or higher. Versions under v14 are known not to work due to language level changes.
:bulb: It is highly recommended to use [Node Version Manager (NVM)](https://github.com/creationix/nvm) to manage your Node.js installation if you’re on a Linux/Unix environment.

Maybe this is something that is obvious to other people, but updating the Manual Installation page to reflect the need for specifically node 14.x would clarify for future users, as having the page still contain install commands for node 12 gives the impression that it is only the version of NVM which needs concern as long as node version is 14.0+

**Comment by NuSkooler** [comment]
@rcmart3q Thanks for the report, got it fixed in the docs.

Sounds like you figured it out and are working properly with Node.js 14+?

**Comment by rcmart3q** [comment]
Perfect thank you Bryan!

**Comment by rcmart3q** [comment]
Sorry for the late response to your question, yes I did get everything working once I specified Node 14. It would not work on any other version. I had chased various runtime errors unsure of what was going on. But then took a shot in the dark and assumed since you wrote your doc around Node 14 that maybe Enigma was hard dependent on this version.

**Comment by NuSkooler** [comment]
@rcmart3q Thanks for the update! I think we missed some 14 requirements in some of the scripts, but I believe they should all be resolved at this point.
