### ISSUE TITLE
Install fails on Ubuntu 22.10

### ISSUE THREAD

**Issue by wirehack7** [NuSkooler/enigma-bbs#474]
**Describe the Bug**

During install via install script the install seems to fail. Install hangs on this line:
```bash
2023-04-18 08:36:30 Installing Node 14 via nvm
v14.21.3 is already installed.
Now using node v14.21.3 (npm v6.14.18)
Now using node v14.21.3 (npm v6.14.18)
2023-04-18 08:36:30 ENiGMA½ is already installed in /home/enigma/enigma-bbs, trying to update using git
2023-04-18 08:36:30 Installing required Node packages...
2023-04-18 08:36:30 Note that on some systems such as RPi, this can take a VERY long time. Be patient!
Already on 'master'
Your branch is up to date with 'origin/master'.
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
[  ................] / fetchMetadata: sill pacote range manifest for delegates@^1.0.0 fetched in 690ms
```

CPU is first at 100%, then idles and nothing happens (waited approx 1 hour)

**To Reproduce**
Any relevant steps to reproduce the behavior:
* Run: `curl -o- https://raw.githubusercontent.com/NuSkooler/enigma-bbs/master/misc/install.sh | bash`

**Expected Behavior**
Install shall be successful

**Actual Behavior**
Install fails

**Environment**
* [ ] I am using Node.js v14.x LTS or higher
* [ ] `npm install` or `yarn` reports success
* Actual Node.js version (`node --version`): none
* Operating system (`uname -a` on *nix systems): Linux BBS 5.15.102-1-pve #1 SMP PVE 5.15.102-1 (2023-03-14T13:48Z) x86_64 x86_64 x86_64 GNU/Linux
* Revision (`git rev-parse --short HEAD`): a208d91d
* Ubuntu CT container
![image](https://user-images.githubusercontent.com/1439039/232723039-ab4ada1c-16d5-4f6f-b206-53ef8f9bbd50.png)

**Comment by wirehack7** [comment]
Waited even longer, resulting in this:

```bash
8990 warn optional SKIPPING OPTIONAL DEPENDENCY: cpu-features@0.0.6 (node_modules/cpu-features):
8991 warn optional SKIPPING OPTIONAL DEPENDENCY: cpu-features@0.0.6 install: `node buildcheck.js > buildcheck.gypi && node-gyp rebuild`
8991 warn optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
8992 verbose optional SKIPPING OPTIONAL DEPENDENCY:
8992 verbose optional Failed at the cpu-features@0.0.6 install script.
8992 verbose optional SKIPPING OPTIONAL DEPENDENCY: This is probably not a problem with npm. There is likely additional logging output above.
8993 verbose stack Error: node-pty@0.10.1 install: `node scripts/install.js`
8993 verbose stack Exit status 1
8993 verbose stack     at EventEmitter.<anonymous> (/home/enigma/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
8993 verbose stack     at EventEmitter.emit (events.js:400:28)
8993 verbose stack     at ChildProcess.<anonymous> (/home/enigma/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
8993 verbose stack     at ChildProcess.emit (events.js:400:28)
8993 verbose stack     at maybeClose (internal/child_process.js:1088:16)
8993 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
8994 verbose pkgid node-pty@0.10.1
8995 verbose cwd /home/enigma/enigma-bbs
8996 verbose Linux 5.15.102-1-pve
8997 verbose argv "/home/enigma/.nvm/versions/node/v14.21.3/bin/node" "/home/enigma/.nvm/versions/node/v14.21.3/bin/npm" "install"
8998 verbose node v14.21.3
8999 verbose npm  v6.14.18
9000 error code ELIFECYCLE
9001 error errno 1
9002 error node-pty@0.10.1 install: `node scripts/install.js`
9002 error Exit status 1
9003 error Failed at the node-pty@0.10.1 install script.
9003 error This is probably not a problem with npm. There is likely additional logging output above.
9004 verbose exit [ 1, true ]
```

**Comment by wirehack7** [comment]
Removed `node_modules` dir, ran install script again. Works now.
