### ISSUE TITLE
ENIGMA crashes if NUA does not collect complete info.

### ISSUE THREAD

**Issue by chilledtonic** [NuSkooler/enigma-bbs#522]
**Describe the Bug**
My understanding was that [this pr](https://github.com/NuSkooler/enigma-bbs/pull/480) made collecting full user information unnecessary; however, if you later open the user config page after having some of these values unset (on my board, I do not collect real name or location), and try to tab past an empty line in the config, the board will hard crash with this error.

```
enigma-bbs/core/text_view.js:156
        text = text.toString();  
```

**To Reproduce**
1. Establish a board where NUA does not collect name or location (or skip any default field)
2. Try to edit the account

**Expected Behavior**

I would prefer either ENIGMA more gracefully handled the empty string.

**Actual Behavior**

Server crashes completely.

**Screenshots**

**Environment**
* [X] I am using Node.js v14.x LTS or higher
* [x] `npm install` or `yarn` reports success

**Comment by NuSkooler** [comment]
@chilledtonic thanks for the report & PR! I should be able to take a look this week.

**Comment by voipmeister** [comment]
Can reproduce on a fresh installation of 0.0.14-beta on a RPi. Going through the application form crashes Enigma on using Tab or Enter. This is the feedback on the console:

`/mybbs/enigma-bbs/core/text_view.js:156
        text = text.toString();
                    ^

TypeError: Cannot read property 'toString' of undefined
    at TextView.setText (/mybbs/enigma-bbs/core/text_view.js:156:21)
    at viewValidationListener (/mybbs/enigma-bbs/core/nua.js:56:32)
    at validateResult (/mybbs/enigma-bbs/core/view_controller.js:395:21)
    at EditTextView.validateNonEmpty [as validate] (/mybbs/enigma-bbs/core/system_view_validate.js:27:12)
    at ViewController.validateView (/mybbs/enigma-bbs/core/view_controller.js:387:18)
    at ViewController.switchFocus (/mybbs/enigma-bbs/core/view_controller.js:525:10)
    at ViewController.nextFocus (/mybbs/enigma-bbs/core/view_controller.js:553:14)
    at EditTextView.ViewController.viewActionListener (/mybbs/enigma-bbs/core/view_controller.js:100:22)
    at EditTextView.emit (events.js:400:28)
    at EditTextView.View.onKeyPress (/mybbs/enigma-bbs/core/view.js:310:18)`

**Comment by NuSkooler** [comment]
Thanks for the report - we have a open ticket on this right now. I've been super busy, but I'll try to pull that in today and get it to master.

**Comment by NuSkooler** [comment]
Just pushed the fixes to this -- note that you will need to change your menu.hjson entries and art files for the NUA and CONF so the fields aren't used!
