### ISSUE TITLE
Empty subject in new mail throws "Cannot read property 'toString' of undefined"

### ISSUE THREAD

**Issue by voipmeister** [NuSkooler/enigma-bbs#528]
**Describe the Bug**
When posting a new message and omitting the subject, Engima crashes with `TypeError: Cannot read property 'toString' of undefined`

**To Reproduce**
Post a new message, leave the subject empty (just skip over it with 'Enter').

**Expected Behavior**
User should be warned about not being able to send a message without a subject.

**Actual Behavior**
Enigma crashes with the error below:
```
/mybbs/enigma-bbs/core/text_view.js:156
        text = text.toString();
                    ^

TypeError: Cannot read property 'toString' of undefined
    at TextView.setText (/mybbs/enigma-bbs/core/text_view.js:156:21)
    at viewValidationListener (/mybbs/enigma-bbs/core/fse.js:171:40)
    at validateResult (/mybbs/enigma-bbs/core/view_controller.js:395:21)
    at EditTextView.validateNonEmpty [as validate] (/mybbs/enigma-bbs/core/system_view_validate.js:27:12)
    at ViewController.validateView (/mybbs/enigma-bbs/core/view_controller.js:387:18)
    at EditTextView.ViewController.viewActionListener (/mybbs/enigma-bbs/core/view_controller.js:107:26)
    at EditTextView.emit (events.js:400:28)
    at EditTextView.View.onKeyPress (/mybbs/enigma-bbs/core/view.js:308:18)
    at EditTextView.onKeyPress (/mybbs/enigma-bbs/core/edit_text_view.js:100:46)
    at TelnetClient.ViewController.clientKeyPressHandler (/mybbs/enigma-bbs/core/view_controller.js:91:34)
```

**Screenshots**
Not really applicable.

**Environment**
* [x] I am using Node.js v14.x LTS or higher
* [x] `npm install` or `yarn` reports success
* Actual Node.js version (`node --version`): `v14.21.3`
* Operating system (`uname -a` on *nix systems): `Linux bbs01 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`
* Revision (`git rev-parse --short HEAD`): `6aa0c867`
* Any additional relevant information about your setup: Syncterm used as a client on macOS; remote running Raspbian (latest on RPi)

**Comment by NuSkooler** [comment]
This was fixed sometime last week: https://github.com/NuSkooler/enigma-bbs/blob/master/core/text_view.js#L154

Can you try pulling? 

```
cd /path/to/enigma-bbs
git pull
# restart your board
```

**Comment by voipmeister** [comment]
Works, thanks!
