### ISSUE TITLE
Problem with oputil.js?

### ISSUE THREAD

**Issue by bbs-addict** [NuSkooler/enigma-bbs#82]
For :bug: bug reports, please fill out the information below plus any additional relevant information. If this is a feature request, feel free to clear the form.

**Short problem description**
Error message see below

**Environment**
- [X ] I am using Node.js v4.x or higher
- [ ] `npm install` reports success
- Actual Node.js version (`node --version`): v5.0.0
- Operating system (`uname -a` on *nix systems):Linux steelbox 4.6.0-040600-generic #201605151930 SMP Sun May 15 23:32:59 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- Revision (`git rev-parse --short HEAD`):9af9bfe

**Expected behavior**
Configure program to run.
**Actual behavior**
It fails.

**Steps to reproduce**
Directly after new installation of all new software.

./oputil.js config --new
module.js:339
    throw err;
    ^

Error: Cannot find module '/home/david/enigma-bbs/node_modules/sqlite3/lib/binding/node-v47-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/david/enigma-bbs/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

**Comment by NuSkooler** [comment]
@bbs-addict Welcome to ENiGMA½ :) 

You're missing the sqlite3 module. You need to run `npm install` first. See the [Quickstart guide](https://github.com/NuSkooler/enigma-bbs/blob/master/docs/index.md#quickstart)
